#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoBaseDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="APF-Inteligencia")]
	public partial class APFInteligenciaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public APFInteligenciaDataContext() : 
				base(global::AccesoBaseDatos.Properties.Settings.Default.APF_InteligenciaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public APFInteligenciaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public APFInteligenciaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public APFInteligenciaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public APFInteligenciaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Abogado> Abogados
		{
			get
			{
				return this.GetTable<Abogado>();
			}
		}
		
		public System.Data.Linq.Table<Puesto> Puestos
		{
			get
			{
				return this.GetTable<Puesto>();
			}
		}
		
		public System.Data.Linq.Table<AdscripciónPolítica> AdscripciónPolíticas
		{
			get
			{
				return this.GetTable<AdscripciónPolítica>();
			}
		}
		
		public System.Data.Linq.Table<CirculoCercano> CirculoCercanos
		{
			get
			{
				return this.GetTable<CirculoCercano>();
			}
		}
		
		public System.Data.Linq.Table<DatosContacto> DatosContactos
		{
			get
			{
				return this.GetTable<DatosContacto>();
			}
		}
		
		public System.Data.Linq.Table<Escolaridad> Escolaridads
		{
			get
			{
				return this.GetTable<Escolaridad>();
			}
		}
		
		public System.Data.Linq.Table<Foto> Fotos
		{
			get
			{
				return this.GetTable<Foto>();
			}
		}
		
		public System.Data.Linq.Table<Funcionario> Funcionarios
		{
			get
			{
				return this.GetTable<Funcionario>();
			}
		}
		
		public System.Data.Linq.Table<InformaciónGeneral> InformaciónGenerals
		{
			get
			{
				return this.GetTable<InformaciónGeneral>();
			}
		}
		
		public System.Data.Linq.Table<OrganigramaFederal> OrganigramaFederals
		{
			get
			{
				return this.GetTable<OrganigramaFederal>();
			}
		}
		
		public System.Data.Linq.Table<PDFPresupuesto> PDFPresupuestos
		{
			get
			{
				return this.GetTable<PDFPresupuesto>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpLoadFuncionarios")]
		public ISingleResult<UpLoadFuncionariosResult> UpLoadFuncionarios()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<UpLoadFuncionariosResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Abogados")]
	public partial class Abogado
	{
		
		private System.Nullable<int> _Id;
		
		private string _Nombre;
		
		private string _Clave;
		
		public Abogado()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int")]
		public System.Nullable<int> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(255)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Clave", DbType="NVarChar(255)")]
		public string Clave
		{
			get
			{
				return this._Clave;
			}
			set
			{
				if ((this._Clave != value))
				{
					this._Clave = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Puestos")]
	public partial class Puesto
	{
		
		private System.Nullable<int> _Id1;
		
		private string _ID;
		
		private System.Nullable<double> _AñoInicial;
		
		private System.Nullable<int> _MesInicial;
		
		private System.Nullable<int> _DiaInicial;
		
		private System.Nullable<double> _AñoFinal;
		
		private System.Nullable<int> _MesFinal;
		
		private System.Nullable<int> _DiaFinal;
		
		private string _DependenciaEntidad;
		
		private string _Puesto1;
		
		private string _JefeInmediantoSuperior;
		
		private string _CurrículumVitae;
		
		private string _CargoActual;
		
		private string _Abogado;
		
		public Puesto()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id1", DbType="Int")]
		public System.Nullable<int> Id1
		{
			get
			{
				return this._Id1;
			}
			set
			{
				if ((this._Id1 != value))
				{
					this._Id1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(255)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AñoInicial", DbType="Float")]
		public System.Nullable<double> AñoInicial
		{
			get
			{
				return this._AñoInicial;
			}
			set
			{
				if ((this._AñoInicial != value))
				{
					this._AñoInicial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MesInicial", DbType="Int")]
		public System.Nullable<int> MesInicial
		{
			get
			{
				return this._MesInicial;
			}
			set
			{
				if ((this._MesInicial != value))
				{
					this._MesInicial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaInicial", DbType="Int")]
		public System.Nullable<int> DiaInicial
		{
			get
			{
				return this._DiaInicial;
			}
			set
			{
				if ((this._DiaInicial != value))
				{
					this._DiaInicial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AñoFinal", DbType="Float")]
		public System.Nullable<double> AñoFinal
		{
			get
			{
				return this._AñoFinal;
			}
			set
			{
				if ((this._AñoFinal != value))
				{
					this._AñoFinal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MesFinal", DbType="Int")]
		public System.Nullable<int> MesFinal
		{
			get
			{
				return this._MesFinal;
			}
			set
			{
				if ((this._MesFinal != value))
				{
					this._MesFinal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaFinal", DbType="Int")]
		public System.Nullable<int> DiaFinal
		{
			get
			{
				return this._DiaFinal;
			}
			set
			{
				if ((this._DiaFinal != value))
				{
					this._DiaFinal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DependenciaEntidad", DbType="NVarChar(255)")]
		public string DependenciaEntidad
		{
			get
			{
				return this._DependenciaEntidad;
			}
			set
			{
				if ((this._DependenciaEntidad != value))
				{
					this._DependenciaEntidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Puesto", Storage="_Puesto1", DbType="NVarChar(255)")]
		public string Puesto1
		{
			get
			{
				return this._Puesto1;
			}
			set
			{
				if ((this._Puesto1 != value))
				{
					this._Puesto1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JefeInmediantoSuperior", DbType="NVarChar(255)")]
		public string JefeInmediantoSuperior
		{
			get
			{
				return this._JefeInmediantoSuperior;
			}
			set
			{
				if ((this._JefeInmediantoSuperior != value))
				{
					this._JefeInmediantoSuperior = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrículumVitae", DbType="NVarChar(255)")]
		public string CurrículumVitae
		{
			get
			{
				return this._CurrículumVitae;
			}
			set
			{
				if ((this._CurrículumVitae != value))
				{
					this._CurrículumVitae = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CargoActual", DbType="NVarChar(255)")]
		public string CargoActual
		{
			get
			{
				return this._CargoActual;
			}
			set
			{
				if ((this._CargoActual != value))
				{
					this._CargoActual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abogado", DbType="NVarChar(255)")]
		public string Abogado
		{
			get
			{
				return this._Abogado;
			}
			set
			{
				if ((this._Abogado != value))
				{
					this._Abogado = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AdscripciónPolítica")]
	public partial class AdscripciónPolítica
	{
		
		private System.Nullable<int> _Id1;
		
		private string _ID;
		
		private System.Nullable<double> _FechaDeInicio;
		
		private System.Nullable<int> _FechaDeFin;
		
		private string _NombreDelPartido;
		
		private string _Abogado;
		
		public AdscripciónPolítica()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id1", DbType="Int")]
		public System.Nullable<int> Id1
		{
			get
			{
				return this._Id1;
			}
			set
			{
				if ((this._Id1 != value))
				{
					this._Id1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(255)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaDeInicio", DbType="Float")]
		public System.Nullable<double> FechaDeInicio
		{
			get
			{
				return this._FechaDeInicio;
			}
			set
			{
				if ((this._FechaDeInicio != value))
				{
					this._FechaDeInicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaDeFin", DbType="Int")]
		public System.Nullable<int> FechaDeFin
		{
			get
			{
				return this._FechaDeFin;
			}
			set
			{
				if ((this._FechaDeFin != value))
				{
					this._FechaDeFin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreDelPartido", DbType="NVarChar(255)")]
		public string NombreDelPartido
		{
			get
			{
				return this._NombreDelPartido;
			}
			set
			{
				if ((this._NombreDelPartido != value))
				{
					this._NombreDelPartido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abogado", DbType="NVarChar(255)")]
		public string Abogado
		{
			get
			{
				return this._Abogado;
			}
			set
			{
				if ((this._Abogado != value))
				{
					this._Abogado = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CirculoCercano")]
	public partial class CirculoCercano
	{
		
		private System.Nullable<int> _Id1;
		
		private string _ID;
		
		private string _Nombre;
		
		private string _Información;
		
		private string _Abogado;
		
		public CirculoCercano()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id1", DbType="Int")]
		public System.Nullable<int> Id1
		{
			get
			{
				return this._Id1;
			}
			set
			{
				if ((this._Id1 != value))
				{
					this._Id1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(255)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(255)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Información", DbType="NVarChar(255)")]
		public string Información
		{
			get
			{
				return this._Información;
			}
			set
			{
				if ((this._Información != value))
				{
					this._Información = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abogado", DbType="NVarChar(255)")]
		public string Abogado
		{
			get
			{
				return this._Abogado;
			}
			set
			{
				if ((this._Abogado != value))
				{
					this._Abogado = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DatosContacto")]
	public partial class DatosContacto
	{
		
		private System.Nullable<int> _Id1;
		
		private string _ID;
		
		private string _Tipo;
		
		private string _dato;
		
		private string _Abogado;
		
		public DatosContacto()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id1", DbType="Int")]
		public System.Nullable<int> Id1
		{
			get
			{
				return this._Id1;
			}
			set
			{
				if ((this._Id1 != value))
				{
					this._Id1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(255)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="NVarChar(255)")]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this._Tipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dato", DbType="NVarChar(255)")]
		public string dato
		{
			get
			{
				return this._dato;
			}
			set
			{
				if ((this._dato != value))
				{
					this._dato = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abogado", DbType="NVarChar(255)")]
		public string Abogado
		{
			get
			{
				return this._Abogado;
			}
			set
			{
				if ((this._Abogado != value))
				{
					this._Abogado = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Escolaridad")]
	public partial class Escolaridad
	{
		
		private System.Nullable<int> _Id1;
		
		private string _ID;
		
		private System.Nullable<double> _AñoInicial;
		
		private System.Nullable<double> _MesInicial;
		
		private System.Nullable<double> _DiaInicial;
		
		private System.Nullable<double> _AñoFinal;
		
		private System.Nullable<double> _MesFinal;
		
		private System.Nullable<double> _DiaFinal;
		
		private string _Universidad;
		
		private string _Grado;
		
		private string _Abogado;
		
		public Escolaridad()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id1", DbType="Int")]
		public System.Nullable<int> Id1
		{
			get
			{
				return this._Id1;
			}
			set
			{
				if ((this._Id1 != value))
				{
					this._Id1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(255)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AñoInicial", DbType="Float")]
		public System.Nullable<double> AñoInicial
		{
			get
			{
				return this._AñoInicial;
			}
			set
			{
				if ((this._AñoInicial != value))
				{
					this._AñoInicial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MesInicial", DbType="Float")]
		public System.Nullable<double> MesInicial
		{
			get
			{
				return this._MesInicial;
			}
			set
			{
				if ((this._MesInicial != value))
				{
					this._MesInicial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaInicial", DbType="Float")]
		public System.Nullable<double> DiaInicial
		{
			get
			{
				return this._DiaInicial;
			}
			set
			{
				if ((this._DiaInicial != value))
				{
					this._DiaInicial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AñoFinal", DbType="Float")]
		public System.Nullable<double> AñoFinal
		{
			get
			{
				return this._AñoFinal;
			}
			set
			{
				if ((this._AñoFinal != value))
				{
					this._AñoFinal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MesFinal", DbType="Float")]
		public System.Nullable<double> MesFinal
		{
			get
			{
				return this._MesFinal;
			}
			set
			{
				if ((this._MesFinal != value))
				{
					this._MesFinal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaFinal", DbType="Float")]
		public System.Nullable<double> DiaFinal
		{
			get
			{
				return this._DiaFinal;
			}
			set
			{
				if ((this._DiaFinal != value))
				{
					this._DiaFinal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Universidad", DbType="NVarChar(255)")]
		public string Universidad
		{
			get
			{
				return this._Universidad;
			}
			set
			{
				if ((this._Universidad != value))
				{
					this._Universidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grado", DbType="NVarChar(255)")]
		public string Grado
		{
			get
			{
				return this._Grado;
			}
			set
			{
				if ((this._Grado != value))
				{
					this._Grado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abogado", DbType="NVarChar(255)")]
		public string Abogado
		{
			get
			{
				return this._Abogado;
			}
			set
			{
				if ((this._Abogado != value))
				{
					this._Abogado = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fotos")]
	public partial class Foto
	{
		
		private string _ID;
		
		private System.Data.Linq.Binary _Foto1;
		
		private string _PhotoType;
		
		private string _Abogado;
		
		public Foto()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(255)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Foto", Storage="_Foto1", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Foto1
		{
			get
			{
				return this._Foto1;
			}
			set
			{
				if ((this._Foto1 != value))
				{
					this._Foto1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotoType", DbType="NVarChar(255)")]
		public string PhotoType
		{
			get
			{
				return this._PhotoType;
			}
			set
			{
				if ((this._PhotoType != value))
				{
					this._PhotoType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abogado", DbType="NVarChar(255)")]
		public string Abogado
		{
			get
			{
				return this._Abogado;
			}
			set
			{
				if ((this._Abogado != value))
				{
					this._Abogado = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Funcionarios")]
	public partial class Funcionario
	{
		
		private System.Nullable<int> _Id1;
		
		private string _ID;
		
		private string _ApellidoPaterno;
		
		private string _ApellidoMaterno;
		
		private string _PrimerNombre;
		
		private string _SegundoNombre;
		
		private string _Nacionalidad;
		
		private System.Nullable<double> _AñoNacimiento;
		
		private System.Nullable<double> _MesNacimiento;
		
		private System.Nullable<double> _DiaNacimiento;
		
		private string _Abogado;
		
		public Funcionario()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id1", DbType="Int")]
		public System.Nullable<int> Id1
		{
			get
			{
				return this._Id1;
			}
			set
			{
				if ((this._Id1 != value))
				{
					this._Id1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(255)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidoPaterno", DbType="NVarChar(255)")]
		public string ApellidoPaterno
		{
			get
			{
				return this._ApellidoPaterno;
			}
			set
			{
				if ((this._ApellidoPaterno != value))
				{
					this._ApellidoPaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidoMaterno", DbType="NVarChar(255)")]
		public string ApellidoMaterno
		{
			get
			{
				return this._ApellidoMaterno;
			}
			set
			{
				if ((this._ApellidoMaterno != value))
				{
					this._ApellidoMaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimerNombre", DbType="NVarChar(255)")]
		public string PrimerNombre
		{
			get
			{
				return this._PrimerNombre;
			}
			set
			{
				if ((this._PrimerNombre != value))
				{
					this._PrimerNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegundoNombre", DbType="NVarChar(255)")]
		public string SegundoNombre
		{
			get
			{
				return this._SegundoNombre;
			}
			set
			{
				if ((this._SegundoNombre != value))
				{
					this._SegundoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nacionalidad", DbType="NVarChar(255)")]
		public string Nacionalidad
		{
			get
			{
				return this._Nacionalidad;
			}
			set
			{
				if ((this._Nacionalidad != value))
				{
					this._Nacionalidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AñoNacimiento", DbType="Float")]
		public System.Nullable<double> AñoNacimiento
		{
			get
			{
				return this._AñoNacimiento;
			}
			set
			{
				if ((this._AñoNacimiento != value))
				{
					this._AñoNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MesNacimiento", DbType="Float")]
		public System.Nullable<double> MesNacimiento
		{
			get
			{
				return this._MesNacimiento;
			}
			set
			{
				if ((this._MesNacimiento != value))
				{
					this._MesNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaNacimiento", DbType="Float")]
		public System.Nullable<double> DiaNacimiento
		{
			get
			{
				return this._DiaNacimiento;
			}
			set
			{
				if ((this._DiaNacimiento != value))
				{
					this._DiaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abogado", DbType="NVarChar(255)")]
		public string Abogado
		{
			get
			{
				return this._Abogado;
			}
			set
			{
				if ((this._Abogado != value))
				{
					this._Abogado = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InformaciónGeneral")]
	public partial class InformaciónGeneral
	{
		
		private System.Nullable<int> _Id1;
		
		private string _ID;
		
		private string _TipoDeInformación;
		
		private string _Referencia;
		
		private string _Abogado;
		
		public InformaciónGeneral()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id1", DbType="Int")]
		public System.Nullable<int> Id1
		{
			get
			{
				return this._Id1;
			}
			set
			{
				if ((this._Id1 != value))
				{
					this._Id1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(255)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoDeInformación", DbType="NVarChar(255)")]
		public string TipoDeInformación
		{
			get
			{
				return this._TipoDeInformación;
			}
			set
			{
				if ((this._TipoDeInformación != value))
				{
					this._TipoDeInformación = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Referencia", DbType="NVarChar(MAX)")]
		public string Referencia
		{
			get
			{
				return this._Referencia;
			}
			set
			{
				if ((this._Referencia != value))
				{
					this._Referencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abogado", DbType="NVarChar(255)")]
		public string Abogado
		{
			get
			{
				return this._Abogado;
			}
			set
			{
				if ((this._Abogado != value))
				{
					this._Abogado = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OrganigramaFederal")]
	public partial class OrganigramaFederal
	{
		
		private System.Nullable<int> _Id1;
		
		private string _TipoRegistro;
		
		private string _NombrePuesto;
		
		private string _ID;
		
		private System.Nullable<double> _Sec;
		
		private string _Abogado;
		
		private System.Nullable<int> _Id1Presupuesto;
		
		public OrganigramaFederal()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id1", DbType="Int")]
		public System.Nullable<int> Id1
		{
			get
			{
				return this._Id1;
			}
			set
			{
				if ((this._Id1 != value))
				{
					this._Id1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoRegistro", DbType="NVarChar(255)")]
		public string TipoRegistro
		{
			get
			{
				return this._TipoRegistro;
			}
			set
			{
				if ((this._TipoRegistro != value))
				{
					this._TipoRegistro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombrePuesto", DbType="NVarChar(255)")]
		public string NombrePuesto
		{
			get
			{
				return this._NombrePuesto;
			}
			set
			{
				if ((this._NombrePuesto != value))
				{
					this._NombrePuesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(255)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sec", DbType="Float")]
		public System.Nullable<double> Sec
		{
			get
			{
				return this._Sec;
			}
			set
			{
				if ((this._Sec != value))
				{
					this._Sec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abogado", DbType="NVarChar(255)")]
		public string Abogado
		{
			get
			{
				return this._Abogado;
			}
			set
			{
				if ((this._Abogado != value))
				{
					this._Abogado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id1Presupuesto", DbType="Int")]
		public System.Nullable<int> Id1Presupuesto
		{
			get
			{
				return this._Id1Presupuesto;
			}
			set
			{
				if ((this._Id1Presupuesto != value))
				{
					this._Id1Presupuesto = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PDFPresupuesto")]
	public partial class PDFPresupuesto
	{
		
		private System.Nullable<int> _Id1;
		
		private string _PDFFileName;
		
		private System.Data.Linq.Binary _PDF;
		
		private string _Abogado;
		
		public PDFPresupuesto()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id1", DbType="Int")]
		public System.Nullable<int> Id1
		{
			get
			{
				return this._Id1;
			}
			set
			{
				if ((this._Id1 != value))
				{
					this._Id1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDFFileName", DbType="NVarChar(255)")]
		public string PDFFileName
		{
			get
			{
				return this._PDFFileName;
			}
			set
			{
				if ((this._PDFFileName != value))
				{
					this._PDFFileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDF", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary PDF
		{
			get
			{
				return this._PDF;
			}
			set
			{
				if ((this._PDF != value))
				{
					this._PDF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abogado", DbType="NVarChar(255)")]
		public string Abogado
		{
			get
			{
				return this._Abogado;
			}
			set
			{
				if ((this._Abogado != value))
				{
					this._Abogado = value;
				}
			}
		}
	}
	
	public partial class UpLoadFuncionariosResult
	{
		
		private System.Nullable<int> _Id1;
		
		private string _ID;
		
		private string _ApellidoPaterno;
		
		private string _ApellidoMaterno;
		
		private string _PrimerNombre;
		
		private string _SegundoNombre;
		
		private string _Nacionalidad;
		
		private System.Nullable<double> _AñoNacimiento;
		
		private System.Nullable<double> _MesNacimiento;
		
		private System.Nullable<double> _DiaNacimiento;
		
		private string _Abogado;
		
		public UpLoadFuncionariosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id1", DbType="Int")]
		public System.Nullable<int> Id1
		{
			get
			{
				return this._Id1;
			}
			set
			{
				if ((this._Id1 != value))
				{
					this._Id1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(255)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidoPaterno", DbType="NVarChar(255)")]
		public string ApellidoPaterno
		{
			get
			{
				return this._ApellidoPaterno;
			}
			set
			{
				if ((this._ApellidoPaterno != value))
				{
					this._ApellidoPaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApellidoMaterno", DbType="NVarChar(255)")]
		public string ApellidoMaterno
		{
			get
			{
				return this._ApellidoMaterno;
			}
			set
			{
				if ((this._ApellidoMaterno != value))
				{
					this._ApellidoMaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimerNombre", DbType="NVarChar(255)")]
		public string PrimerNombre
		{
			get
			{
				return this._PrimerNombre;
			}
			set
			{
				if ((this._PrimerNombre != value))
				{
					this._PrimerNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegundoNombre", DbType="NVarChar(255)")]
		public string SegundoNombre
		{
			get
			{
				return this._SegundoNombre;
			}
			set
			{
				if ((this._SegundoNombre != value))
				{
					this._SegundoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nacionalidad", DbType="NVarChar(255)")]
		public string Nacionalidad
		{
			get
			{
				return this._Nacionalidad;
			}
			set
			{
				if ((this._Nacionalidad != value))
				{
					this._Nacionalidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AñoNacimiento", DbType="Float")]
		public System.Nullable<double> AñoNacimiento
		{
			get
			{
				return this._AñoNacimiento;
			}
			set
			{
				if ((this._AñoNacimiento != value))
				{
					this._AñoNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MesNacimiento", DbType="Float")]
		public System.Nullable<double> MesNacimiento
		{
			get
			{
				return this._MesNacimiento;
			}
			set
			{
				if ((this._MesNacimiento != value))
				{
					this._MesNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaNacimiento", DbType="Float")]
		public System.Nullable<double> DiaNacimiento
		{
			get
			{
				return this._DiaNacimiento;
			}
			set
			{
				if ((this._DiaNacimiento != value))
				{
					this._DiaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abogado", DbType="NVarChar(255)")]
		public string Abogado
		{
			get
			{
				return this._Abogado;
			}
			set
			{
				if ((this._Abogado != value))
				{
					this._Abogado = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
