IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_NAME = N'UpLoadFotos')
BEGIN
   DROP PROCEDURE [dbo].[UpLoadFotos]
END 
go
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[UpLoadFotos]
AS
BEGIN
	SET NOCOUNT ON;
	SELECT * FROM [dbo].[Fotos]
END
GO