IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_NAME = N'UpLoadPuestos')
BEGIN
   DROP PROCEDURE [dbo].[UpLoadPuestos]
END 
go
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[UpLoadPuestos]
AS
BEGIN
	SET NOCOUNT ON;
	SELECT * FROM [dbo].[Puestos]
END
GO