IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_NAME = N'UpLoadDatosContacto')
BEGIN
   DROP PROCEDURE [dbo].[UpLoadDatosContacto]
END 
go
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[UpLoadDatosContacto]
AS
BEGIN
	SET NOCOUNT ON;
	SELECT * FROM [dbo].[DatosContacto]
END
GO
