IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_NAME = N'UpLoadCirculoCercano')
BEGIN
   DROP PROCEDURE [dbo].[UpLoadCirculoCercano]
END 
go
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[UpLoadCirculoCercano]
AS
BEGIN
	SET NOCOUNT ON;
	SELECT * FROM [dbo].[CirculoCercano]
END
GO
