IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_NAME = N'UpLoadEscolaridad')
BEGIN
   DROP PROCEDURE [dbo].[UpLoadEscolaridad]
END 
go
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[UpLoadEscolaridad]
AS
BEGIN
	SET NOCOUNT ON;
	SELECT * FROM [dbo].[Escolaridad]
END
GO