IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_NAME = N'UpLoadPDFPresupuesto')
BEGIN
   DROP PROCEDURE [dbo].[UpLoadPDFPresupuesto]
END 
go
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[UpLoadPDFPresupuesto]
AS
BEGIN
	SET NOCOUNT ON;
	SELECT * FROM [dbo].[PDFPresupuesto]
END
GO