IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_NAME = N'UpLoadFuncionarios')
BEGIN
   DROP PROCEDURE [dbo].[UpLoadFuncionarios]
END 
go
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[UpLoadFuncionarios]
AS
BEGIN
	SET NOCOUNT ON;
	SELECT * FROM [dbo].[Funcionarios]
END
GO
